# Generated by Django 2.1.5 on 2019-11-03 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('club', models.TextField(choices=[('G', 'General'), ('K', 'Key Club')], db_index=True, default='G')),
                ('contactName', models.TextField()),
                ('contactPhone', models.TextField()),
                ('dateCompleted', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('accurate', models.BooleanField()),
                ('performedByID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
